deploy:
    stage: deploy
    only:
        - master
deploy:
  script:
    - apt-get update -qq && apt-get install -y -qq lftp
    - lftp -c "set ftp:ssl-allow no; open -u $USERNAME,$PASSWORD $HOST; mirror -Rev ./ ./  --ignore-time --parallel=10 --exclude-glob .git* --exclude .git/ --exclude README.md --exclude .gitignore --exclude /node_modules --exclude /public/hot --exclude /public/storage --exclude /storage/*.key --exclude /vendor --exclude .env --exclude .env.backup --exclude .phpunit.result.cache --exclude Homestead.json --exclude Homestead.yaml --exclude npm-debug.log --exclude yarn-error.log"