image: ubuntu:18.04

before_script:
  - apt-get update -qy
  - apt-get install -y lftp

build:
  script:
    - lftp -e "set ftp:ssl-allow no; open $HOST; user $USERNAME $PASSWORD; mirror -X .* -X .*/ --reverse --verbose --parallel=10;"